---
title: "charlottefile"
author: "Charlotte Coudert"
date: "2022-12-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(haven)
GSS2018 <- read_sav("GSS2018.sav")
View(GSS2018)
```

```{r}
relig_data2 <- GSS2018 %>% select(RELIG, DENOM,OTHER,OTHJEW,JEW,JEWAJ,FUND,ATTEND,MAATTEND,PAATTEND,SPATTEND,RELITEN,RELINTENA,POSTLIFE,POSTLF1,POSTLF2,POSTLF3,POSTLF4,POSTLF5,POSTLF6,POSTLF7,POSTLF8,POSTLF9,POSTLF10,LIFEDIFF,MINDBODY,RESTACT,PALEFUL,PRAY,JUDGE,REDEEMER,LOVER,MASTER,MOTHER,CREATOR,FATHER,SPOUSE,FRIEND,KING,LIBERATR,HEARLER,MAPA,MATERSP,JUDGELUV,FRNDKING,CRTRHEAL,RDEELIB,POPESPKS,RELIG16,DENOM16,OTH16,OTHJEW16,JEW16,JEW16AJ,FUND16,SPREL,SPDEN,SPOTHER,SPOTHJEW,SPFUND16,SPDEN16,SPOTH16,COREL,CODEN,COOTHER,COJEW,COFUND,TITHING,PRAYER,PRAYERY,PRAYERX,BIBLE,BIBLEY,FEPRIEST,FECLERGY,RELGRADE,CONCLERG,CONMEDIC,CONJUDGE,CONSCI,CONLEGIS,SWITCHED,SWITCH1,SWITCH2,SWITCH3,SWITNUM,SWITAGE1,SWITAGE2,SWITWHY1, SWITWHY2,MARELIG,MADEN,MAOTH,MAJEW,MAFUND,PARELIG,PADEN,PAOTH,PAJEW,PAFUND,CHURHSCH,SUNSCH16,GRACE16,JOIN16,LAPSED,CHURHMEM,CHURHACT,TVRELIG,GOD,REBORN,SAVESOUL,SAYGRADE,READWORD,PUNSIN,DECBIBLE,DECCHURH,GOCHURCH,BELIEVE,FOLLOW,MYFAITH,MADATGOD,DOUBTS1,DOUBTS2,DOUBTS3,DOUBTS4,FAITH1,FAITH2,FAITH3,FAITH4,FRNDCON1,FRNDCON2,FRNDCON3,FRNDCON4,FRNDCON5,FRNDREL1,FRNDREL2,FRNDREL3,FRNDREL4,FRNDREL5,GODSELLS,GODSPORT,GIVECONG,GIVEREL,GIVEOTH,RELHRS1,RELHRS2,IMPLIVES,OBEYTCH,PREACH,FEKIDS5,CHNANG7,VOLRELIG,HRSRELIG,TOTRELIG,VALRELIG,COPE2,COPE3,COPE4,COPE5,COPE6,GODWATCH,FORGIVE3,FEELGOD,RELCMFRT,UNIONGOD,GODLOVE,RELPERSN,RELEXP,ARTGOD,RELIG30,AGERELEX,CHNGEREL,NUMRBORN,AGERBORN,CHNGRBRN,ENTITY,EXPCHNG1,EXPCHNG2,EXPCHNG3,WHYCHNG1,WHYCHNG2,WHYCHNG3,CHANGED1,CHANGED2,CHANGED3,RELALT1,RELALT2,RELALT3,RELALT4,RELALT5,RELALT6,JOYLIFTS,RELSPRT1,RELSPRT2,GODHELP,GODGUIDE,GODLVDIR,GODLVOTH,BLESSNGS,CLOSRGOT,GODCLOSE,IDOLS,NOTTHINK,RELNEG,GRPCHURH,OPRELIG,CONCHURH,POLSGOD,CLERGGOV,RELIGPUB,CHURHPOW,GODCHNGE,AFTERLIF,DEVIL,HEAVEN,HELL,MIRACLES,BIBLE1,THEISM,FATALISM,GODMEANS,PREDETER,RELEXPER,MARELKID,PARELKID,MADENKID,PADENKID,RELIGKID,DENKID,ATTENDMA,ATTENDPA,ATTEND12,PRAYFREQ,RELACTIV,RELSCRPT,FELLREL,SCHLPRAY,GODRIGHT,ANTIREL,RELTRUTH,COMFORT,RELPAST,RELRLVNT,) ##IF WE WANT KID'S RELIGION- PG 81
##DOUBTS3 is "HAS SCIENCE-FAITH CONFLICT CAUSED DOUBT"!!!!
##SCIFAITH,HARMGOOD,NATURGOD <- MAYBE TOO CLOSE TO RESPONSE
```


```{r}
library(haven)
library(dplyr)
library(stringr)
library(purrr)
GSS2018 <- read_sav("GSS2018.sav")
View(GSS2018)
```

```{r}
n <- ncol(GSS2018)
labels_vector <- map_chr(1:n, function(x) attr(GSS2018[[x]], "label"))
variable_name <- names(GSS2018)
code_book <- data.frame(variable_name, description = labels_vector)

relig_codebook <- code_book[grep("relig|strength of affiliation|god|jew|denomination|fundamentalist|bible|muslim|belief|church|pray", labels_vector, ignore.case = TRUE),]

code_book[grep("scientific", labels_vector, ignore.case = TRUE),]

relig_df <- GSS2018 %>% 
  select(relig_codebook$variable_name, CONSCI)

View(relig_df)
```

```{r}
library(tree)
library(gbm)
library(randomForest)
```

```{r}
tree <- tree(as.factor(CONSCI) ~., data = small_data)
prune_tree <- prune.tree(tree, best = 8)
plot(tree)
text(tree, pretty = 0)
summary(tree)
#boost.cars <- gbm( ~., data = small_data, 
#                    distribution = "gaussian", n.trees = 1000,
#                    interaction.depth = 3)

#bag <- randomForest(CONSCI~., data = small_data, ntree = 100,
#                           mtry = 11, importance = TRUE)'
#                    

```

```{r}
small_data = relig_df %>% 
  select(CONSCI, ATTEND, BIBLE, FUND, FUND16, GOD, PRAY, RELACTIV, RELIG, RELIG16, RELITEN, RELPERSN) #%>%
  #mutate(consci = as.factor(CONSCI))
summary(small_data)
```

```{r}
fit <- glm(as.factor(CONSCI) ~ .,data=small_data, family=binomial(link="logit"))
summary(fit)
plot(fit)
```
```{r}
hist(small_data$GOD)
```

```{r}
hist(relevel_df$CONSCI_re)
hist(relevel_df$PRAY)
hist(relevel_df$ATTEND)
```

```{r}
#plot(GSS2018$FUND, type = "h", color= GSS2018$DOUBT3)
plot(GSS2018$FUND, GSS2018$CONCHURH)
```

